### ISSUE TITLE
如何编译go-rdma

### ISSUE THREAD

**Issue by zhangchuanqing5658** [tidb-incubator/TiDBOverRoCE#2]
1、是否需要编译rdma-core？我看了接口形式一致，理论不需要编译rdma-core，不知道理解是否正确
2、go-rdma编译的时候，runtime在退出cgo是出现panic，需要特殊版本吗？

**Comment by zhangchuanqing5658** [comment]
atal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f8a8d31e05f]

runtime stack:
runtime.throw(0x793537, 0x2a)
        /home/zhangcq/rdma_demo/rsocket/go-rdma/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
        /home/zhangcq/rdma_demo/rsocket/go-rdma/src/runtime/signal_unix.go:718 +0x2e5


goroutine 231 [syscall]:
runtime.cgocall(0x6ee510, 0xc000135910, 0xc00000a901)
        /home/zhangcq/rdma_demo/rsocket/go-rdma/src/runtime/cgocall.go:154 +0x5b fp=0xc0001358e0 sp=0xc0001358a8 pc=0x4066fb
rdma._C2func_rwrite(0x1a, 0xc00000a900, 0xf3, 0x0, 0x0, 0x0)
        _cgo_gotypes.go:302 +0x51 fp=0xc000135910 sp=0xc0001358e0 pc=0x5a21f1
rdma.RWrite.func1(0x1a, 0xc0001359a0, 0x77, 0x0, 0x0)
        /home/zhangcq/rdma_demo/rsocket/go-rdma/src/rdma/fd_unix.go:396 +0x9e fp=0xc000135960 sp=0xc000135910 pc=0x5a361e
rdma.RWrite(0x1a, 0xc00000a900, 0xf3, 0x100, 0x0, 0x100, 0x3000)

**Comment by zhangchuanqing5658** [comment]
使用修改后的Net库，编译pingpong程序，在开启4个以上连接的时候直接崩溃，不知道有没有测试过

**Comment by raygift** [comment]
> 1、是否需要编译rdma-core？我看了接口形式一致，理论不需要编译rdma-core，不知道理解是否正确 2、go-rdma编译的时候，runtime在退出cgo是出现panic，需要特殊版本吗？

之前测试基于仓库中的 rdma-core和 golang版本，对于其他版本的兼容性未经过测试；

**Comment by raygift** [comment]
> 使用修改后的Net库，编译pingpong程序，在开启4个以上连接的时候直接崩溃，不知道有没有测试过

使用的是什么版本的 golang 与 rdma-core？

**Comment by zhangchuanqing5658** [comment]
4个以上连接的时候直接崩溃：只使用了golang，rdma-core使用的英伟达推荐的驱动版本
